name: Check composer, run tests with cov report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    permissions:
      write-all

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Check PHP installation
      run: php -m
      
    - name: Check PHP packages
      run: dpkg --get-selections | grep -i php
    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        dev: yes
        
    - name: Run PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6.7
        php_version: 7.3
        php_extensions: xdebug
        bootstrap: vendor/autoload.php
        configuration: test/utils/phpunit.xml
        args: --coverage-text
      env:
        XDEBUG_MODE: coverage
        

      
      
