name: Run tests and cov report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    permissions:
      write-all

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      uses: php-actions/composer@v6
        
    - name: Run PHPUnit Tests
      id: unitTests
      uses: php-actions/phpunit@master
      with:
        php_version: 7.3
        php_extensions: xdebug
        bootstrap: vendor/autoload.php
        configuration: test/utils/phpunit.xml
        testdox_xml: test/coverage.xml
        args: --coverage-text
        
    - name: Codecov upload
      if: ${{ steps.unitTests.outcome == 'success' }}
      uses: codecov/codecov-action@v3
      with:
        files: test/coverage.xml
